### ISSUE TITLE
ROG Control Center - Permission issues

### ISSUE THREAD

**Issue by FrantaNautilus** [ublue-os/bluefin#1298]
### Describe the bug

On the latest channel of `bluefin-dx-asus-nvidia` the  `rog-control-center` cannot be started as user, nor as superuser (extensions disabled). Two separate errors are produced based on whether `sudo` is used.

1.  Without `sudo` error "Permission denied": `$ RUST_BACKTRACE=full rog-control-center `.
```
thread 'main' panicked at rog-control-center/src/main.rs:50:39:
called `Result::unwrap()` on an `Err` value: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }
stack backtrace:
   0:     0x5608f2a840ce - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hbf3511293b3072d4
   1:     0x5608f2359b2c - core::fmt::write::hb276ebab965f503a
   2:     0x5608f2a52bd2 - std::io::Write::write_fmt::h0c1d574aec58e4a0
   3:     0x5608f2a8970f - std::sys_common::backtrace::print::hcedf978e05feb4ac
   4:     0x5608f2a88f18 - std::panicking::default_hook::{{closure}}::h9632069b5fabea71
   5:     0x5608f2a89ff0 - std::panicking::rust_panic_with_hook::h963e59e90ed80f7c
   6:     0x5608f2a89a60 - std::panicking::begin_panic_handler::{{closure}}::h46d482f088032edf
   7:     0x5608f2a899b6 - std::sys_common::backtrace::__rust_end_short_backtrace::h2952a37729ebb4e8
   8:     0x5608f2a899a3 - rust_begin_unwind
   9:     0x5608f22bfed4 - core::panicking::panic_fmt::h5663ee5bb5d5c59a
  10:     0x5608f22c02f2 - core::result::unwrap_failed::hdaf878459c642445
  11:     0x5608f23130d9 - rog_control_center::main::{{closure}}::hd7467b59e4738bcb
  12:     0x5608f23080fa - rog_control_center::main::hab47692ad9e33ebf
  13:     0x5608f22f6456 - std::sys_common::backtrace::__rust_begin_short_backtrace::h48d2a55a88e67ee5
  14:     0x5608f23138be - main
  15:     0x7f73fafd0088 - __libc_start_call_main
  16:     0x7f73fafd014b - __libc_start_main_impl
  17:     0x5608f22f3755 - _start
  18:                0x0 - <unknown>
Aborted (core dumped)
```
2. With `sudo`, "Tray unable to be initialised" :  `$ sudo rog-control-center`
```
[ERROR rog_control_center::tray] Tray unable to be initialised: TrayError: Os(InputOutput(Os { code: 2, kind: NotFound, message: "No such file or directory" }))
    	at /builddir/build/BUILD/asusctl-6.0.6/vendor/betrayer/src/platform/linux/mod.rs:57:20. Do you have a system tray enabled?
thread 'main' panicked at rog-control-center/src/main.rs:209:40:
called `Result::unwrap()` on an `Err` value: Other("Could not initialize backend.\nError from Winit backend: Error initializing winit event loop: os error at /builddir/build/BUILD/asusctl-6.0.6/vendor/winit/src/platform_impl/linux/mod.rs:786: neither WAYLAND_DISPLAY nor WAYLAND_SOCKET is set; note: enable the `winit/x11` feature to support X11\nError from LinuxKMS backend: Error opening session with libseat: Function not implemented\nNo backends configured.")
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Aborted
```

### What did you expect to happen?

1.  `rog-control-center` starts (without errors).
2.  `rog-control-center` can be started as user, not superuser. 

### Output of `rpm-ostree status`

```shell
State: idle
AutomaticUpdates: stage; rpm-ostreed-automatic.timer: no runs since boot
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bluefin-dx-asus-nvidia:latest
                   Digest: sha256:ed8475ec4bbb1c3fd1c2980ac69f844b203690546d1db5c1aaac585392e1a209
                  Version: 40.20240513.0 (2024-05-13T18:06:35Z)

  ostree-image-signed:docker://ghcr.io/ublue-os/bluefin-dx-asus-nvidia:latest
                   Digest: sha256:2092d942a3a88544e31e97c3d0b2da12afa01efb819c4479cbb2267531426ced
                  Version: 40.20240503.0 (2024-05-03T16:25:40Z)

  ostree-image-signed:docker://ghcr.io/ublue-os/bluefin-dx-asus-nvidia:latest
                   Digest: sha256:484f9e9b8f3cbefbd5ed3e0b86a840b462d9aa982e387a6fd507f8749c7ac805
                  Version: 40.20240423.0 (2024-04-24T14:54:21Z)
                   Pinned: yes
```

### Output of `groups`

```shell
myuser wheel docker lxd incus-admin libvirt
```

### Extra information or context

# System
output of `inxi -Fx`
```
System:
  Kernel: 6.8.9-666.rog.fc40.x86_64 arch: x86_64 bits: 64 compiler: gcc
    v: 2.41-34.fc40
  Desktop: GNOME v: N/A Distro: Wolfi
Machine:
  Type: Laptop System: ASUSTeK product: ROG Zephyrus G14 GA401QM_GA401QM
    v: 1.0 serial: <superuser required>
  Mobo: ASUSTeK model: GA401QM v: 1.0 serial: <superuser required>
    UEFI: American Megatrends LLC. v: GA401QM.408 date: 05/13/2021
Battery:
  ID-1: BAT0 charge: 54.8 Wh (95.6%) condition: 57.3/76.0 Wh (75.5%)
    volts: 15.8 min: 15.8 model: ASUSTeK ASUS Battery status: discharging
CPU:
  Info: 8-core model: AMD Ryzen 9 5900HS with Radeon Graphics bits: 64
    type: MT MCP arch: Zen 3 rev: 0 cache: L1: 512 KiB L2: 4 MiB L3: 16 MiB
  Speed (MHz): avg: 586 high: 1397 min/max: 400/4680 cores: 1: 1396 2: 400
    3: 400 4: 1397 5: 400 6: 400 7: 400 8: 400 9: 400 10: 400 11: 400 12: 400
    13: 1397 14: 400 15: 400 16: 400 bogomips: 105411
  Flags: avx avx2 ht lm nx pae sse sse2 sse3 sse4_1 sse4_2 sse4a ssse3 svm
Graphics:
  Message: Required tool lspci not installed. Check --recommends
  Display: wayland server: N/A compositor: gnome-shell driver: N/A
    resolution: no compositor data
  API: EGL Message: EGL data requires eglinfo. Check --recommends.
Audio:
  Message: No device data found.
  API: ALSA v: k6.8.9-666.rog.fc40.x86_64 status: kernel-api
Network:
  Message: Required tool lspci not installed. Check --recommends
  IF-ID-1: tailscale0 state: unknown speed: -1 duplex: full mac: N/A
  IF-ID-2: wlp2s0 state: up mac: <filter>
Bluetooth:
  Device-1: MediaTek Wireless_Device driver: btusb v: 0.8 type: USB
    bus-ID: 3-4:3
  Report: rfkill ID: hci0 rfk-id: 0 state: up address: see --recommends
Drives:
  Local Storage: total: 953.87 GiB used: 67.6 GiB (7.1%)
  ID-1: /dev/nvme0n1 vendor: SK Hynix model: HFM001TD3JX013N
    size: 953.87 GiB temp: 28.9 C
Partition:
  Message: No partition data found.
Swap:
  ID-1: swap-1 type: zram size: 8 GiB used: 0 KiB (0.0%) dev: /dev/zram0
Sensors:
  Src: /sys System Temperatures: cpu: 43.9 C mobo: 34.0 C gpu: amdgpu
    temp: 43.0 C
  Fan Speeds (rpm): N/A
Info:
  Memory: total: 32 GiB note: est. available: 30.75 GiB used: 3.32 GiB (10.8%)
  Processes: 418 Uptime: 14m Init: systemd
  Packages: 183 Compilers: gcc: 13.2.0 Shell: Bash v: 5.2.21 inxi: 3.3.34
```

# Expected cause of problem
The latest update brought `rog-control-center` version 6, which seems to have issues in situations where version 5 worked.

# Previous issues
This issue was preceded by problems with `rog-control-center` version 5, where the program could not be started without `sudo`. When started without `sudo`, `rog-control-center` gave "Permission denied" error below.
```
thread 'main' panicked at rog-control-center/src/main.rs:180:39:
called `Result::unwrap()` on an `Err` value: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }
stack backtrace:
   0:     0x559c83eb9599 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h107faefc94c77012
   1:     0x559c83a69fe0 - core::fmt::write::h453f927c8788e8ad
   2:     0x559c83e81aa1 - std::io::Write::write_fmt::h1abdf1b52633ad54
   3:     0x559c83ebb2be - std::sys_common::backtrace::print::hf49a4eb04fb21139
   4:     0x559c83eba9e0 - std::panicking::default_hook::{{closure}}::h6471197d15e93e55
   5:     0x559c83ebbc23 - std::panicking::rust_panic_with_hook::h78d153760d0851d0
   6:     0x559c83ebb610 - std::panicking::begin_panic_handler::{{closure}}::he79ddabedad3721d
   7:     0x559c83ebb566 - std::sys_common::backtrace::__rust_end_short_backtrace::h5371d05ae7d0d46d
   8:     0x559c83ebb55f - rust_begin_unwind
   9:     0x559c838e5d74 - core::panicking::panic_fmt::h316a44f38297e4ae
  10:     0x559c838e62e2 - core::result::unwrap_failed::h40d0468330705072
  11:     0x559c8392ccae - rog_control_center::main::hf6c19180e24750b4
  12:     0x559c83911556 - std::sys_common::backtrace::__rust_begin_short_backtrace::hc9e4c9e8869affeb
  13:     0x559c8392d7b4 - main
  14:     0x7f0fb6c14088 - __libc_start_call_main
  15:     0x7f0fb6c1414b - __libc_start_main_impl
  16:     0x559c83911215 - _start
  17:                0x0 - <unknown>
Aborted (core dumped)
```

**Comment by FrantaNautilus** [comment]
Update seems to have removed the kernel arguments for nvidia dGPU. Running `ujust nvidia` to add kernel arguments solved the problem.
