### ISSUE TITLE
KCLI does not have support for Python 3.13

### ISSUE THREAD

**Issue by tulilirockz** [ublue-os/bluefin#1890]
Getting this on bluefin-dx:latest 41.20241103.0

```
~> kcli --help                                                                                                                                        11/05/2024 01:47:31 PM
Traceback (most recent call last):
  File "/usr/bin/kcli", line 33, in <module>
    sys.exit(load_entry_point('kcli==99.0', 'console_scripts', 'kcli')())
             ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/kcli", line 25, in importlib_load_entry_point
    return next(matches).load()
           ~~~~~~~~~~~~~~~~~~^^
  File "/usr/lib64/python3.13/importlib/metadata/__init__.py", line 179, in load
    module = import_module(match.group('module'))
  File "/usr/lib64/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1022, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/usr/lib/python3.13/site-packages/kvirt/cli.py", line 20, in <module>
    from kvirt.config import Kconfig
  File "/usr/lib/python3.13/site-packages/kvirt/config.py", line 22, in <module>
    from kvirt.expose import Kexposer
  File "/usr/lib/python3.13/site-packages/kvirt/expose/__init__.py", line 2, in <module>
    from kvirt.bottle import Bottle, request, static_file, jinja2_view, response
  File "/usr/lib/python3.13/site-packages/kvirt/bottle.py", line 71, in <module>
    import base64, calendar, cgi, email.utils, functools, hmac, itertools,\
           mimetypes, os, re, tempfile, threading, time, warnings, weakref, hashlib
ModuleNotFoundError: No module named 'cgi'
```

**Comment by tulilirockz** [comment]
Just found out the `cgi` module is deprecated on python3.13. If KCLI doesnt get updated it probably should be deleted since it will just use the deprecated API

**Comment by tulilirockz** [comment]
KCLI works now!
